import os

OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY", "")
OPENWEATHER_URL = "https://api.openweathermap.org/data/2.5/weather"
OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast"
NOAA_ERDDAP_BASE = "https://coastwatch.pfeg.noaa.gov/erddap"
NOAA_DATASET_ID = "erdQMekm1day"
SENTINELHUB_CLIENT_ID = os.getenv("SENTINELHUB_CLIENT_ID", "")
SENTINELHUB_CLIENT_SECRET = os.getenv("SENTINELHUB_CLIENT_SECRET", "")
SENTINELHUB_INSTANCE_ID = os.getenv("SENTINELHUB_INSTANCE_ID", "")
SATELLITE_IMAGE_WIDTH = int(os.getenv("SATELLITE_IMAGE_WIDTH", "768"))
SATELLITE_IMAGE_HEIGHT = int(os.getenv("SATELLITE_IMAGE_HEIGHT", "768"))
REQUEST_TIMEOUT_SECONDS = float(os.getenv("REQUEST_TIMEOUT_SECONDS", "15"))
WIND_DRAG_FACTOR = float(os.getenv("WIND_DRAG_FACTOR", "0.03"))
EXTERNAL_API_MAX_RETRIES = int(os.getenv("EXTERNAL_API_MAX_RETRIES", "3"))
EXTERNAL_API_BACKOFF_SECONDS = float(os.getenv("EXTERNAL_API_BACKOFF_SECONDS", "1.5"))
